typography_spectrum: 0.7449627055320889
color:
  brandStrength: 0.5892843708861619
  lightness: 0.9084711039904505
  saturation: 0.7414366616867483
  rhythmicContrast: 0.13476506806910038
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.5549553311429918
author:
  name: Arne
  email: hallo@arnebrockmann.com
name: Griddish
navigation:
  - name: 'Finlandia Caviar Shop and Restaurant, Helsinki, Finland '
    id: 14b2750a-d439-4805-ae1a-fd22b6e3ae80
    type: content
title: This is a bold Title
description: This is an italic Tagline
